### ISSUE TITLE
Do you plan to update your plugin for Sketch 40?

### ISSUE THREAD

**Issue by edge0703** [KrevedAccky/SketchSplitDivide#3]
I want to mention it in The Sketch Handbook (http://www.sketch-handbook.com/), but only if it works with the current version of Sketch.

**Comment by KrevedAccky** [comment]
I'll check it on Sketch 40. When are you planning to release the book?

**Comment by edge0703** [comment]
It's supposed to come out at the end of November, but edits can only made until the end of October.

Thanks for your effort.

**Comment by KrevedAccky** [comment]
I've updated the plugin, but it became less powerful with the latest Sketch version. Anyway, it still may be useful for somebody.

**Comment by edge0703** [comment]
Thanks, man.

**Comment by edge0703** [comment]
By the way, why does Split not work anymore?

**Comment by KrevedAccky** [comment]
That's because the "Flatten" behaviour was changed - you cannot flatten shape when the result contains more than one path. Perhaps I would find another way to do it.

**Comment by edge0703** [comment]
Didn't know that this was changed, as there was no word about it in the release notes. 

But if you could find a workaround that would be great. However there's really no pressure.
